project:
  type: website
  output-dir: docs
  render:
    - index.qmd

website:
  title: "ppd"
  site-url: "https://jimianelli.github.io/ppd/"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 2

